Add install instructions for gentoo
rtrlib/handbook pull request #2
Opened 2018-01-08 14:37 UTC by mroethke

2018-01-09 08:09 UTC, smlng requested changes
minor wording nits

2018-01-09 08:09 UTC, smlng commented on source/usage.rst
> +First you have to setup layman [#layman]_, then you can install rtrlib with the following commands:
for consistency (and brevity) skip `you` like above in the macOS + Homebrew instructions.

2018-01-09 08:09 UTC, smlng commented on source/usage.rst
> +The kind guys from the Frrouting project maintain a gentoo overlay [#overlay]_ that contains an ebuild for rtrlib.
typos (?) please fix/replace `/Frrouting/FRRouting/` and `/rtrlib/the RTRlib/`

2018-12-14 11:54 UTC, mroethke commented
ping @smlng

2018-12-14 12:11 UTC, smlng commented
please squash

2018-12-14 12:11 UTC, smlng approved these changes

2018-12-14 12:14 UTC, mroethke commented
Done

2018-12-14 12:15 UTC, merged